Traceback (most recent call last):
  File "/mnt/nfs/home/nca121/mambaforge/envs/naglmbis/lib/python3.12/site-packages/pandas/core/internals/blocks.py", line 1429, in setitem
    values[indexer] = casted
    ~~~~~~^^^^^^^^^
ValueError: NumPy boolean array indexing assignment cannot assign 2406 input values to the 1 output values where the mask is true

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nca121/nagl-mbis/scripts/data/nagl_datasets/append_parquets.py", line 42, in <module>
    pandas_parquet.loc[pandas_parquet['smiles'] == tagged_smiles, 'esp_column'] = record[0].esp.tolist()
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nfs/home/nca121/mambaforge/envs/naglmbis/lib/python3.12/site-packages/pandas/core/indexing.py", line 911, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/mnt/nfs/home/nca121/mambaforge/envs/naglmbis/lib/python3.12/site-packages/pandas/core/indexing.py", line 1942, in _setitem_with_indexer
    self._setitem_with_indexer_split_path(indexer, value, name)
  File "/mnt/nfs/home/nca121/mambaforge/envs/naglmbis/lib/python3.12/site-packages/pandas/core/indexing.py", line 1982, in _setitem_with_indexer_split_path
    self._setitem_with_indexer_2d_value(indexer, value)
  File "/mnt/nfs/home/nca121/mambaforge/envs/naglmbis/lib/python3.12/site-packages/pandas/core/indexing.py", line 2057, in _setitem_with_indexer_2d_value
    self._setitem_single_column(loc, value_col, pi)
  File "/mnt/nfs/home/nca121/mambaforge/envs/naglmbis/lib/python3.12/site-packages/pandas/core/indexing.py", line 2175, in _setitem_single_column
    self.obj._mgr.column_setitem(loc, plane_indexer, value)
  File "/mnt/nfs/home/nca121/mambaforge/envs/naglmbis/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 1337, in column_setitem
    new_mgr = col_mgr.setitem((idx,), value)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nfs/home/nca121/mambaforge/envs/naglmbis/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 415, in setitem
    return self.apply("setitem", indexer=indexer, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nfs/home/nca121/mambaforge/envs/naglmbis/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 363, in apply
    applied = getattr(b, f)(**kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/nfs/home/nca121/mambaforge/envs/naglmbis/lib/python3.12/site-packages/pandas/core/internals/blocks.py", line 1432, in setitem
    raise ValueError(
ValueError: setting an array element with a sequence.
